version: '3.1'

services:

  db:
    container_name: mariadb-11.3.2-jammy
    image: mariadb:11.3.2-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: dockertestdb
      ports:
        -3308:3306

  adminer:
    container_name: adminer-11.3.2-jammy
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 9080:8080